### ISSUE TITLE
Windows portable app?

### ISSUE THREAD

**Issue by pomazanbohdan** [webyaml/core#4]
Standalone app from py2exe?

https://stackoverflow.com/questions/41570359/how-can-i-convert-a-py-to-exe-for-python

**Comment by webyaml** [comment]
At the present time the only supported OS for webyaml is Linux.  This is only because it has not been tested in other environments.  There is a strong case that most of webyaml will work in other OSes because python core developers, and the community, release modules that handle each OS's idiosyncrasies while keeping the python code uniform.  However there may very well be unintended consequences when webyaml code meets different OSes.  For instance things such as line breaks and escape characters may not be interpreted in the same way.

Code "freezers" such as py2exe are incompatible with webyaml.  Programs like py2exe analyze the python code looking for python import statements to determine dependencies.  After the dependencies are determined the application code is packaged with a custom version of python and all dependent modules.

Because Webyaml itself is like a programming language, it does not arbitrarily load all modules that can be used with webyaml.  Webyaml dynamically imports modules only when a web page requires it.  This is designed to keep memory usage down and to give webyaml users the ability to create their own custom python modules without the need to alter the core webyaml code.
